workflows:
    react-native:
        name: reactnativetest
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
          vars:
            XCODE_WORKSPACE: "Niko.xcworkspace"
            XCODE_SCHEME: "Niko"
          xcode: latest
          node: latest
          cocoapods: default
        scripts:
          - name: Install dependencies, Expo CLI and eject app
            script: |
              yarn install
              yarn global add expo-cli
              npx expo prebuild --clean --platform ios --skip-dependency-update react-native,react 
          - name: Set Info.plist values
            script: |
              PLIST=$FCI_BUILD_DIR/$XCODE_SCHEME/Info.plist
              PLIST_BUDDY=/usr/libexec/PlistBuddy
              $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
          - name: Install CocoaPods dependencies
            script: |
              cd ios && pod install
          - name: Build .app
            script: |
              cd $HOME/clone/ios
              xcodebuild build \
                -workspace "$XCODE_WORKSPACE" \
                -scheme "$XCODE_SCHEME" \
                -sdk iphoneos \
                -configuration Release \
                CODE_SIGN_IDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGNING_ALLOWED=NO 
        artifacts:
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
